### ISSUE TITLE
Move Block not working WP 5.5.1

### ISSUE THREAD

**Issue by effigy11** [advanced-bootstrap-blocks/advanced-bootstrap-blocks#4]
Hi, The ability to drag and drop blocks no longer works in Wordpress 5.5.1 - Winding back to WP 5.4.2 (my previous version) seems to fix the issue.

**Comment by shrthnd** [comment]
@effigy11, thank you for reporting this bug, and for using Advanced Bootstrap Blocks!

Did you find this issue exists with _all_ ABB blocks? 

Testing in Firefox and Chrome this morning, it looks like the "is-drop-target" class is never added to the Container blocks. I don't have an immediate solution (I think this is javascript-related but need to do some testing and research to isolate the issue.)

From what I can see, the drop-zone indicator for the Row and Column blocks appears correctly when moving blocks _within_  Containers the nested Rows/Columns. I am also able to drag/drop Containers blocks between any other block which is not a Container. 

It's less than ideal for your workflow but, as a workaround, the up/down arrows should let you rearrange Container blocks.

**Comment by shrthnd** [comment]
Thanks again for submitting this, @effigy11. I published a change this morning (ABB v1.5) which I think resolves the drag/drop issue in WordPress 5.5.1. Please let me know if this gives you any more trouble.

**Comment by effigy11** [comment]
@shrthnd, thanks for looking into this. Love the plugin BTW. 
That change doesn't seem to work for me. The drag and drop menu still doesn't appear. I'm running a test site with only Advanced Boostrap Blocks and TwentyTwenty as the theme, so there shouldn't be any conflicts from other plugins.

**Comment by effigy11** [comment]
@shrthnd, Sorry my bad... I see that the drag and drop function has moved to the up and down arrows rather than it's own toolbar as previous. It seems to be working for me now. Thanks!

**Comment by shrthnd** [comment]
No worries, @effigy11. Thanks for using Advanced Bootstrap Blocks!
